// @generated by `pnpm fate generate`
import type {
  AppRouter,
  ChatRoomMessage,
  Comment,
  Post,
  Profile,
  User,
} from '@app/server/src/router.ts';
import { createTRPCProxyClient } from '@trpc/client';
import { inferRouterInputs, inferRouterOutputs } from '@trpc/server';
import { createClient, createTRPCTransport, mutation } from 'react-fate';

type TRPCClientType = ReturnType<typeof createTRPCProxyClient<AppRouter>>;
type RouterInputs = inferRouterInputs<AppRouter>;
type RouterOutputs = inferRouterOutputs<AppRouter>;

export const createFateClient = (options: {
  links: Parameters<typeof createTRPCProxyClient>[0]['links'];
}) => {
  const trpcClient = createTRPCProxyClient<AppRouter>(options);

  const mutations = {
    'chatroommessage.add': (client: TRPCClientType) => client.chatroommessage.add.mutate,
    'chatroommessage.delete': (client: TRPCClientType) => client.chatroommessage.delete.mutate,
    'chatroommessage.edit': (client: TRPCClientType) => client.chatroommessage.edit.mutate,
    'comment.add': (client: TRPCClientType) => client.comment.add.mutate,
    'comment.delete': (client: TRPCClientType) => client.comment.delete.mutate,
    'post.like': (client: TRPCClientType) => client.post.like.mutate,
    'post.unlike': (client: TRPCClientType) => client.post.unlike.mutate,
    'profile.update': (client: TRPCClientType) => client.profile.update.mutate,
    'user.update': (client: TRPCClientType) => client.user.update.mutate,
  } as const;

  return createClient({
    mutations: {
      'chatroommessage.add': mutation<
        ChatRoomMessage,
        RouterInputs['chatroommessage']['add'],
        RouterOutputs['chatroommessage']['add']
      >('ChatRoomMessage'),
      'chatroommessage.delete': mutation<
        ChatRoomMessage,
        RouterInputs['chatroommessage']['delete'],
        RouterOutputs['chatroommessage']['delete']
      >('ChatRoomMessage'),
      'chatroommessage.edit': mutation<
        ChatRoomMessage,
        RouterInputs['chatroommessage']['edit'],
        RouterOutputs['chatroommessage']['edit']
      >('ChatRoomMessage'),
      'comment.add': mutation<
        Comment,
        RouterInputs['comment']['add'],
        RouterOutputs['comment']['add']
      >('Comment'),
      'comment.delete': mutation<
        Comment,
        RouterInputs['comment']['delete'],
        RouterOutputs['comment']['delete']
      >('Comment'),
      'post.like': mutation<Post, RouterInputs['post']['like'], RouterOutputs['post']['like']>(
        'Post',
      ),
      'post.unlike': mutation<
        Post,
        RouterInputs['post']['unlike'],
        RouterOutputs['post']['unlike']
      >('Post'),
      'profile.update': mutation<
        Profile,
        RouterInputs['profile']['update'],
        RouterOutputs['profile']['update']
      >('Profile'),
      'user.update': mutation<
        User,
        RouterInputs['user']['update'],
        RouterOutputs['user']['update']
      >('User'),
    },
    transport: createTRPCTransport<AppRouter, typeof mutations>({
      byId: {
        ChatRoom:
          (client: TRPCClientType) =>
          ({
            args,
            ids,
            select,
          }: {
            args?: Record<string, unknown>;
            ids: Array<string | number>;
            select: Array<string>;
          }) =>
            client.chatroom.byId.query({
              args,
              ids: ids.map(String),
              select,
            }),
        ChatRoomMessage:
          (client: TRPCClientType) =>
          ({
            args,
            ids,
            select,
          }: {
            args?: Record<string, unknown>;
            ids: Array<string | number>;
            select: Array<string>;
          }) =>
            client.chatroommessage.byId.query({
              args,
              ids: ids.map(String),
              select,
            }),
        Comment:
          (client: TRPCClientType) =>
          ({
            args,
            ids,
            select,
          }: {
            args?: Record<string, unknown>;
            ids: Array<string | number>;
            select: Array<string>;
          }) =>
            client.comment.byId.query({
              args,
              ids: ids.map(String),
              select,
            }),
        Post:
          (client: TRPCClientType) =>
          ({
            args,
            ids,
            select,
          }: {
            args?: Record<string, unknown>;
            ids: Array<string | number>;
            select: Array<string>;
          }) =>
            client.post.byId.query({
              args,
              ids: ids.map(String),
              select,
            }),
        Profile:
          (client: TRPCClientType) =>
          ({
            args,
            ids,
            select,
          }: {
            args?: Record<string, unknown>;
            ids: Array<string | number>;
            select: Array<string>;
          }) =>
            client.profile.byId.query({
              args,
              ids: ids.map(String),
              select,
            }),
        User:
          (client: TRPCClientType) =>
          ({
            args,
            ids,
            select,
          }: {
            args?: Record<string, unknown>;
            ids: Array<string | number>;
            select: Array<string>;
          }) =>
            client.user.byId.query({
              args,
              ids: ids.map(String),
              select,
            }),
      },
      client: trpcClient,
      lists: {
        chatRoomMessageSearch: (client: TRPCClientType) => client.chatroommessage.search.query,
        chatRooms: (client: TRPCClientType) => client.chatroom.list.query,
        commentSearch: (client: TRPCClientType) => client.comment.search.query,
        posts: (client: TRPCClientType) => client.post.list.query,
        profileByUserId: (client: TRPCClientType) => client.profile.byUserId.query,
      },
      mutations,
    }),
    types: [
      {
        fields: {
          user: { type: 'User' },
        },
        type: 'Profile',
      },
      {
        fields: {
          profile: { type: 'Profile' },
        },
        type: 'User',
      },
      {
        fields: {
          adminsInChatRoom: { listOf: 'User' },
          chatRoomMessagesInChatRooms: { listOf: 'ChatRoomMessage' },
          usersInChatRoom: { listOf: 'User' },
        },
        type: 'ChatRoom',
      },
      {
        fields: {
          author: { type: 'User' },
          chatRoom: { type: 'ChatRoom' },
        },
        type: 'ChatRoomMessage',
      },
      {
        fields: {
          author: { type: 'User' },
          comments: { listOf: 'Comment' },
        },
        type: 'Post',
      },
      {
        fields: {
          author: { type: 'User' },
          post: { type: 'Post' },
        },
        type: 'Comment',
      },
    ],
  });
};
