// @generated by `pnpm fate generate`
import type {
  AppRouter,
  ChatRoom,
  ChatRoomMessage,
  Comment,
  Post,
  Profile,
} from '@app/server/src/router.ts';
import { createTRPCProxyClient } from '@trpc/client';
import { inferRouterInputs, inferRouterOutputs } from '@trpc/server';
import { createClient, createTRPCTransport, mutation } from 'react-fate';

type TRPCClientType = ReturnType<typeof createTRPCProxyClient<AppRouter>>;
type RouterInputs = inferRouterInputs<AppRouter>;
type RouterOutputs = inferRouterOutputs<AppRouter>;

const mutations = {
  'chatRoom.create': mutation<
    ChatRoom,
    RouterInputs['chatRoom']['create'],
    RouterOutputs['chatRoom']['create']
  >('ChatRoom'),
  'chatRoomMessage.add': mutation<
    ChatRoomMessage,
    RouterInputs['chatRoomMessage']['add'],
    RouterOutputs['chatRoomMessage']['add']
  >('ChatRoomMessage'),
  'chatRoomMessage.delete': mutation<
    ChatRoomMessage,
    RouterInputs['chatRoomMessage']['delete'],
    RouterOutputs['chatRoomMessage']['delete']
  >('ChatRoomMessage'),
  'chatRoomMessage.edit': mutation<
    ChatRoomMessage,
    RouterInputs['chatRoomMessage']['edit'],
    RouterOutputs['chatRoomMessage']['edit']
  >('ChatRoomMessage'),
  'comment.add': mutation<Comment, RouterInputs['comment']['add'], RouterOutputs['comment']['add']>(
    'Comment',
  ),
  'comment.delete': mutation<
    Comment,
    RouterInputs['comment']['delete'],
    RouterOutputs['comment']['delete']
  >('Comment'),
  'post.like': mutation<Post, RouterInputs['post']['like'], RouterOutputs['post']['like']>('Post'),
  'post.unlike': mutation<Post, RouterInputs['post']['unlike'], RouterOutputs['post']['unlike']>(
    'Post',
  ),
  'profile.update': mutation<
    Profile,
    RouterInputs['profile']['update'],
    RouterOutputs['profile']['update']
  >('Profile'),
} as const;

type GeneratedClientMutations = typeof mutations;

declare module 'react-fate' {
  interface ClientMutations extends GeneratedClientMutations {}
}

export const createFateClient = (options: {
  links: Parameters<typeof createTRPCProxyClient>[0]['links'];
}) => {
  const trpcClient = createTRPCProxyClient<AppRouter>(options);

  const trpcMutations = {
    'chatRoom.create': (client: TRPCClientType) => client.chatRoom.create.mutate,
    'chatRoomMessage.add': (client: TRPCClientType) => client.chatRoomMessage.add.mutate,
    'chatRoomMessage.delete': (client: TRPCClientType) => client.chatRoomMessage.delete.mutate,
    'chatRoomMessage.edit': (client: TRPCClientType) => client.chatRoomMessage.edit.mutate,
    'comment.add': (client: TRPCClientType) => client.comment.add.mutate,
    'comment.delete': (client: TRPCClientType) => client.comment.delete.mutate,
    'post.like': (client: TRPCClientType) => client.post.like.mutate,
    'post.unlike': (client: TRPCClientType) => client.post.unlike.mutate,
    'profile.update': (client: TRPCClientType) => client.profile.update.mutate,
  } as const;

  return createClient({
    mutations,
    transport: createTRPCTransport<AppRouter, typeof trpcMutations>({
      byId: {
        ChatRoom:
          (client: TRPCClientType) =>
          ({
            args,
            ids,
            select,
          }: {
            args?: Record<string, unknown>;
            ids: Array<string | number>;
            select: Array<string>;
          }) =>
            client.chatRoom.byId.query({
              args,
              ids: ids.map(String),
              select,
            }),
        ChatRoomMessage:
          (client: TRPCClientType) =>
          ({
            args,
            ids,
            select,
          }: {
            args?: Record<string, unknown>;
            ids: Array<string | number>;
            select: Array<string>;
          }) =>
            client.chatRoomMessage.byId.query({
              args,
              ids: ids.map(String),
              select,
            }),
        Comment:
          (client: TRPCClientType) =>
          ({
            args,
            ids,
            select,
          }: {
            args?: Record<string, unknown>;
            ids: Array<string | number>;
            select: Array<string>;
          }) =>
            client.comment.byId.query({
              args,
              ids: ids.map(String),
              select,
            }),
        Post:
          (client: TRPCClientType) =>
          ({
            args,
            ids,
            select,
          }: {
            args?: Record<string, unknown>;
            ids: Array<string | number>;
            select: Array<string>;
          }) =>
            client.post.byId.query({
              args,
              ids: ids.map(String),
              select,
            }),
        Profile:
          (client: TRPCClientType) =>
          ({
            args,
            ids,
            select,
          }: {
            args?: Record<string, unknown>;
            ids: Array<string | number>;
            select: Array<string>;
          }) =>
            client.profile.byId.query({
              args,
              ids: ids.map(String),
              select,
            }),
      },
      client: trpcClient,
      queries: {
        profile: (client: TRPCClientType) => client.profile.byUserId.query,
      },
      lists: {
        chatRoomMessages: (client: TRPCClientType) => client.chatRoomMessage.list.query,
        chatRoomMessageSearch: (client: TRPCClientType) => client.chatRoomMessage.search.query,
        chatRooms: (client: TRPCClientType) => client.chatRoom.list.query,
        commentSearch: (client: TRPCClientType) => client.comment.search.query,
        posts: (client: TRPCClientType) => client.post.list.query,
      },
      mutations: trpcMutations,
    }),
    types: [
      {
        fields: {
          user: { type: 'User' },
        },
        type: 'Profile',
      },
      {
        fields: {
          profile: { type: 'Profile' },
        },
        type: 'User',
      },
      {
        fields: {
          author: { type: 'User' },
          chatRoom: { type: 'ChatRoom' },
        },
        type: 'ChatRoomMessage',
      },
      {
        fields: {
          adminsInChatRoom: { listOf: 'User' },
          chatRoomMessages: { listOf: 'ChatRoomMessage' },
          usersInChatRoom: { listOf: 'User' },
        },
        type: 'ChatRoom',
      },
      {
        fields: {
          author: { type: 'User' },
          comments: { listOf: 'Comment' },
        },
        type: 'Post',
      },
      {
        fields: {
          author: { type: 'User' },
          post: { type: 'Post' },
        },
        type: 'Comment',
      },
    ],
  });
};
